spring:
  application:
    name: api-gateway
  security:
    user:
      name: user
      password: password
  cloud:
    gateway:
      routes:
        - id: Docenti
          uri: http://localhost:8080  # Sostituisci con l'URL effettivo del tuo servizio
          predicates:
            - Path=/api/docenti/**
          filters:
            - StripPrefix=1
            - RewritePath=/api/docenti/(?<segment>.*), /docenti/$\{segment}

        - id: Discenti
          uri: http://localhost:8080  # Sostituisci con l'URL effettivo del tuo servizio
          predicates:
            - Path=/api/discenti/**
          filters:
            - StripPrefix=1
            - RewritePath=/api/discenti/(?<segment>.*), /discenti/$\{segment}

        - id: corsi-service
          uri: http://localhost:8081  # Sostituisci con l'URL effettivo del tuo servizio
          predicates:
            - Path=/api/corsi/**
          filters:
            - StripPrefix=1
            - RewritePath=/api/corsi/(?<segment>.*), /corsi/$\{segment}

server:
  port: 9090