server:
  port: 9090

spring:
  application:
    name: api-gateway

  datasource:
    url: jdbc:postgresql://localhost:5433/securitydb
    username: postgres
    password: Argolone92!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    gateway:
      server:
        webmvc:
          routes:
          - id: docenti
            uri: http://localhost:8080
            predicates:
              - Path=/docenti/**
          - id: discenti
            uri: http://localhost:8080
            predicates:
              - Path=/discenti/**
          - id: corsi-service
            uri: http://localhost:8081
            predicates:
              - Path=/corsi/**
